### ISSUE TITLE
Parenthesized bindings are not supported

### ISSUE THREAD

**Issue by clshortfuse** [alessiopcc/node-bindings-loader#2]
The regex 

````js
const bindings_regex = /\brequire\((?:'bindings'|"bindings")\)\s*\(([^)]*)\)/g;
const node_gyp_build_regex = /\brequire\((?:'node-gyp-build'|"node-gyp-build")\)\s*\(([^)]*)\)/g;
````

doesn't balance parentheses. So the following fails:

* `require('node-gyp-build')(path.join(__dirname, '..'));`
* `require('node-gyp-build')(('file.node'));`

**Comment by clshortfuse** [comment]
See: https://github.com/node-ffi-napi/node-ffi-napi/blob/bc95086c0e462c0be8f264f86e4c16b48c824243/lib/bindings.js#L8

**Comment by alessiopcc** [comment]
Thanks, this use case is fixed now
